# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Build
on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      # https://github.com/pre-commit/action
      - uses: pre-commit/action@v3.0.1

  mkdocs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: requirements.txt

      # Cache lychee results to avoid hitting rate limits
      # https://lychee.cli.rs/github_action_recipes/caching/
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Install lychee
        run: |
          LYCHEE_VERSION=0.20.1
          mkdir -p ~/.local/bin
          curl -sfL https://github.com/lycheeverse/lychee/releases/download/lychee-v${LYCHEE_VERSION}/lychee-x86_64-unknown-linux-gnu.tar.gz | tar -zxf - -C ~/.local/bin lychee

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Build docs
        run: |
          make build

      - name: Internal link check
        run: |
          make linkcheck-internal

      - name: Full link check
        run: |
          make linkcheck
